### ISSUE TITLE
Level select feature implementation just like PS1

### ISSUE THREAD

**Issue by rahul5162Volt** [LostArtefacts/TR1X#1060]
It would be better to add level select feature just like in PS1 version.

**Comment by walkawayy** [comment]
If you press the right arrow key on any of your saves while in the load game passport, you can access the level select menu.

![image](https://github.com/LostArtefacts/TR1X/assets/81546780/4f7adc23-dda0-4ba0-b2e2-e3490ba9d0f7)

**Comment by walkawayy** [comment]
Gonna close this since we have level select per save file, a dev console to type in whatever level you'd like, and a cheat option and input combo to skip levels.
