### ISSUE TITLE
Feature request: don't clip pickup sprites when z-buffer is on

### ISSUE THREAD

**Issue by Defrago** [LostArtefacts/TR1X#22]
This game engine has many problems with Sprites and Objects being cut by geometry in a places they shouldn't. Workaround for Pickup Sprites could be is elevating pickups rendering position above ground a bit. 

[Example](https://github.com/Arsunt/TR2Main/commit/f749a673148c6aec202cd99311782db6b787c557)

**Comment by rr-** [comment]
Closing as it's better captured in #819.
