### ISSUE TITLE
Feature request: add loading screens like the PSX version.

### ISSUE THREAD

**Issue by Storm3000** [LostArtefacts/TR1X#358]
Is it possible to add the loading screens from PSX version to Tomb1Main?

The Tomb2Main project already did it and it looks great.

**Comment by Richard-L** [comment]
I would love this, obviously 😇

Pertains to my asset importer under "discussions", as I personally don't think these should just be included (how TR2M does it).

**Comment by Richard-L** [comment]
Maybe for some added context, I compiled the images together in a strip.

PS1
![psx loading screens](https://user-images.githubusercontent.com/4934209/150336015-26f119d4-18a2-45f6-b3e1-060c70aef38c.png)

Saturn
![saturn loading screens](https://user-images.githubusercontent.com/4934209/150336045-fda8d2b5-65da-4750-a2e4-3057dfca0fe5.png)

^ you can see how curiously Saturn has a different loading screen for the "Greece" level group. It is more telling of its first Francis' Folly level, as you can see Lara having to enter on top of the mountain, to then find the folly has a part leading all the way down. 

PS1 images:
`.RAW` container, each 384x256px resolution

Saturn images:
`.BIN` container, each 320x256px resolution

I can document the full set of images in https://github.com/rr-/Tomb1Main/discussions/247 if you like. There are 9 PS1 files, 13 Saturn, latter including things like a Sega logo, the beta TR1 main menu backdrop, etc.

**Comment by rr-** [comment]
It would be nice to have each image as a separate PNG and I'd appreciate documenting it in the related discussion.

I'm leaning towards just bundling it with the game. For the music we went with external hosting unaffiliated with this repository, but I don't think anybody's going to make much fuss about those 5 images.

**Comment by atombraiderfan** [comment]
@Richard-L Have you seen the collection of TR1 loading screens at this site: [https://core-design.com/goodies_tr1_loadingscreens.html](https://core-design.com/goodies_tr1_loadingscreens.html).  There seems to be a set of screens without the 'loading' text overlaid.

**Comment by Richard-L** [comment]
@atombraiderfan oh nice, yes I do remember seeing them but forgot. Thanks for linking.

@rr- since this appears to be a legit source from what looks to be core, should these images just be included? I can outline later where each of them appear on PS1/Saturn

**Comment by ArhumMK** [comment]
I'd love to have these loading screens even if they appear for a fraction of a second due to modern hardware. You could limit the appearance of these loading screens to level transitions only. So loading saves within a level will not show these, Or the loading screens only appear when you start a new chapter, i.e Greece loading screen before it's first level only.
