### ISSUE TITLE
Feature request: Animate sprite sequence 193 (Plant 3)

### ISSUE THREAD

**Issue by Rapora9** [LostArtefacts/TR1X#449]
In Cistern and Tomb of Tihocan, there is a sprite sequence 193 called _Plant 3._ These plants are found in many water areas like here (Cistern, central pool) and here (Tomb of Tihocan, after the long slide).

![Näyttökuva (348)](https://user-images.githubusercontent.com/97730054/155405025-d1c6f045-b71b-4b6c-a261-3b8f6489050d.png)
![Näyttökuva (349)](https://user-images.githubusercontent.com/97730054/155405037-f674eacd-6f5e-469a-b792-eff34d86a058.png)

As you see in this video, the sprite has actually 4 frames that play out a waving animation.

https://user-images.githubusercontent.com/97730054/155404864-e6d256c1-ced8-4b9d-a283-536ce6639de4.mp4

Yet, none of these plants are moving. And it also seems – as supported by the screenshots above – that all of the plants use the first frame. I have found no variation. This is the case on Ps1 too (based on some YouTube videos I watched).

Why are the extra frames not used, neither for animation or for having different looking plants? In the lack of better knowledge, I guess it's an error from Core. It would be nice to utilise them and that's why I'm requesting to animate the plants and bring them to life.

If you have more information or explanation what are the extra frames for, be sure to share it :)

A word of warning though. At least in custom level building when playing with sprites, they tend to break stuff in unexpected ways. So, if something is done to this, be careful? []:

**Comment by Richard-L** [comment]
Another interesting find Rapora.

I'm guessing they wanted them animated but noticed it looked too overdone in-game, and then stuck with the first frame
