### ISSUE TITLE
Feature: Underwater music behaviour options

### ISSUE THREAD

**Issue by Richard-L** [LostArtefacts/TR1X#528]
Basically identical to TR2Main's feature, control for music tracks to behave differently if the camera is underwater:
1. Mute music (you only hear underwater SFX like Lara's swimming, or crocs attacking, etc)
2. Make half volume (or even less, I'm not sure exactly what level TR2 sets here)
3. Play at full volume (= same as if camera isn't underwater, current behaviour, PS1 behaviour)
4. Only mute ambient tracks but play music tracks at full volume.
5. Only mute ambient tracks but play music tracks at half volume.

Curiously the DOS version of TR1 behaves like 1. And in fact it does add a little bit of immersion if the music responds to the level's surroundings. Consider UB's first level where you drop into water, and then don't hear the wind ambient whilst the camera is following you underwater.

**Comment by walkawayy** [comment]
@aredfan and @Richard-L could you test this build out? I looked at TR2Main's option and used those. Full, quiet, and mute while underwater.

[underwater_v1 TR1X-4.2-42-g871259d-dirty-Windows.zip](https://github.com/user-attachments/files/16571165/underwater_v1.TR1X-4.2-42-g871259d-dirty-Windows.zip)

**Comment by aredfan** [comment]
@walkawayy The main menu music can be affected by these settings.

**To reproduce:** 

1. Set Underwater music behaviour to `None` or `Quiet`.
2. Load Lara's Home and teleport to room 14.
3. Make sure Lara's camera is underwater.
4. Quit and return to the main menu.
